### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by re-fort** [javascript-obfuscator/webpack-obfuscator#10]
"Maximum call stack size exceeded" is displayed in Chrome's console.

Is there any way to avoid it?
Here's the [reproduction](https://github.com/re-fort/obfuscation-test)

**Comment by sanex3339** [comment]
I look on it now

**Comment by sanex3339** [comment]
So, here no logical errors.

`selfDefending` option is ON by default.
This option inserts few additional parts of code into obfuscated code. This additional code will cause to runtime errors **if this code will be changed in various ways after obfuscation**

Right now here two main checks:
1) check for beautifying. Self defended obfuscated code should be in one line. If no - runtime error.
2) check for beautifying of strings which converted to `unicode escape sequence`. Self defending code requires that string should be like `'\x61\x62\x63'`. If string will be converted to the normal view (`'abc'`) - runtime error.

So, you have `selfDefending` option ON and after obfuscation you using `uglifyjs` which convert all unicode escape sequences to it's normal view, so code gives you runtime error.

You have two ways: disable `selfDefending` or use `webpack-obfuscator` plugin last in the row of plugins.


https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/templates/custom-nodes/self-defending-nodes/self-defending-unicode-node/SelfDefendingTemplate.ts#L24

**Comment by re-fort** [comment]
Thanks for your quick reply and  understandable explanations!
Both your suggestions work correctly on my product :)

> From my side i should correctly represent in README what self defended code shouldn't be uglified or changed in any way.

This is a good description to avoid a misunderstanding like me ;)

> And i need to think - maybe i should to disable selfDefending option by default, because this is not first problem with misunderstanding of what this option is enabled by default.

This is also a good change I think.
Using `webpack -p` commands, the same error occurs.
Alyhough that reason is what you said, it might be hard to notice.

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.8.3` and `webpack-obfuscator@0.8.3` is out.
`selfDefending` option now disabled by default and added warning to the readme above option description
