### ISSUE TITLE
How to use in conjunction with DefinePlugin?

### ISSUE THREAD

**Issue by rafaeleyng** [javascript-obfuscator/webpack-obfuscator#103]
Hello

How to use this project in conjunction with plugins such as Webpack's DefinePlugin (https://webpack.js.org/plugins/define-plugin/)?

My config is like:

```js
module.exports = {
  plugins: [
    new webpack.DefinePlugin({
      'process.env.SOME_VAR': JSON.stringify('some-value'),
    }),
  ],
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: [
          {
            loader: WebpackObfuscator.loader,
            options: {
              controlFlowFlattening: true,
              controlFlowFlatteningThreshold: 0.3,

              deadCodeInjection: true,
              deadCodeInjectionThreshold: 0.1,

              identifierNamesGenerator: 'hexadecimal',

              numbersToExpressions: true,

              selfDefending: true,

              splitStrings: true,
              splitStringsChunkLength: 5,
              shuffleStringArray: true,
              rotateStringArray: true,
              stringArray: true,
              stringArrayThreshold: 0.6,
            },
          },
          'babel-loader',
        ],
      },
    ],
  },
}
```

My understanding is that the DefinePlugin will look for exact matches of `process.env.SOME_VAR` and replace it statically with `'some-value'`, like:

```
if (process.env.SOME_VAR === 'some-value') {
  console.log('will do')
}

// which becomes, after DefinePlugin
if ('some-value' === 'some-value') {
  console.log('will do')
}

// which becomes, after optimizations
console.log('will do')
```

But it seems that in conjunction with the obfuscator, my `if` becomes:

```
process[_0x4ff33b('0x14')][_0x4ff33b('0x17') + _0x4ff33b('0xf')] === _0x4ff33b('0x11') + 'value' && console['log'](_0x4ff33b('0x1f') + 'do');
```

So it seems that the DefinePlugin will not be able to find `process.env.SOME_VAR` because it is now in fact `process[_0x4ff33b('0x14')][_0x4ff33b('0x17') + _0x4ff33b('0xf')]`.

How to solve this? I think is something to do with the order that things execute (making the DefinePlugin execute before the obfuscator should solve it), but I could not find an explanation of Webpack's execution steps that I could actually understand.

Just to clarify, I'm using the obfuscator as a loader. I wasn't able to make it work as a plugin (no idea why).

Packages versions:
```
  "javascript-obfuscator": "2.9.4",
  "webpack": "5.10.3",
  "webpack-cli": "4.2.0",
  "webpack-obfuscator": "3.1.0"
```

Thanks a lot!

**Comment by rafaeleyng** [comment]
I think of:
> making the DefinePlugin execute before the obfuscator should solve it
as being the better solution.

Another solution would be some rule to avoid obfuscating some pattern (where I could register `process.env.SOMETHING`).

I'm now playing with conditional comments, but that would be the worst option since I would have to add A LOT of comments in my project.

**Comment by sanex3339** [comment]
I would be happy if you create a PR with the fix

**Comment by rafaeleyng** [comment]
I could try, but I would need heavily some input 😅 , both in terms of Webpack and the obfuscator.

For instance, as expressed in the first post, I really don't understand the order of execution of Webpack loaders vs plugins. Could you give me some input on that?

**Comment by sanex3339** [comment]
I didn't research how orders of plugins are work in webpack@5.
Currently obfuscator is using Compilation.PROCESS_ASSETS_STAGE_DERIVED stage

**Comment by rafaeleyng** [comment]
Thanks, I will try to investigate further. Can't promise that I will be able to create something useful, though.

I'm originally using Webpack 4, just updated to 5 while trying to fix this issue. So doesn't seem to be a Webpack 5 related issue, since it happened on 4 also.

**Comment by rafaeleyng** [comment]
I ended up solving this somewhat easily with conditional comments and centralizing some configs in my application instead of spreading `process.env` in several places, so I will not invest in further investigating this.

I think the issue is still relevant, but feel free to close it if you prefer.

**Comment by sanex3339** [comment]
I think i have to use the latest assets stage `PROCESS_ASSETS_STAGE_REPORT`.

**Comment by sanex3339** [comment]
Released as 3.3.0. Please try it.

**Comment by rafaeleyng** [comment]
@sanex3339 Thanks. I no longer work on that project, so unfortunately I cannot test it anymore.

**Comment by mbenford** [comment]
@sanex3339 would it be possible to backport this change to 2.6.0, so people using webpack 4 could use it as well?

**Comment by sanex3339** [comment]
@mbenford currently i'm using `emit` hook for webpack@4. I'm not sure which hook I should use as the fix, because while using `afterEmit` hook, files already created and obfuscation does not make any effect.

**Comment by sanex3339** [comment]
Changed stage on PROCESS_ASSETS_STAGE_SUMMARIZE
