### ISSUE TITLE
Loader versus Plugin?

### ISSUE THREAD

**Issue by Slapbox** [javascript-obfuscator/webpack-obfuscator#109]
Is the main use of the loader to be able to choose which files to obfuscate, whereas plugin obfuscates everything except explicitly excluded file names? Are there other uses? Or is there any way to exclude `node_modules` with the plugin?

**Comment by sanex3339** [comment]
The loader runs for each file individually, whereas the plugin runs over the complete bundle.

**Comment by Slapbox** [comment]
@sanex3339 how can you tell with certainty that the obfuscation has taken place when using the loader method?

For example, we use `stringArray`, and it's always been easy to tell that it was applied when we previously used `javascript-obfuscator` to obfuscate the entire file - similar to using the Webpack plugin method.

But when we're using the loader method, the output looks quite different. Specifically we used to see a lot of variable names like `_0x8a12db`, but now we see like `Yg[hg(502)]`

Maybe it has to do with `stringArrayWrappersType` and the output of `stringArray` looking different that I expect? I'm coming from `javascript-obfuscator@0.24.5`.

Can you provide some clarity? Thank you again for how much work you've put into this project and for sharing it and supporting it!

**Comment by Slapbox** [comment]
Derp, it occurred to me this is because TerserJS runs afterwards to minify and optimize. I assume though that that would partially undo some of the obfuscation measures?

**Comment by sanex3339** [comment]
For TerserJS you have to use the plugin, which runs after the TerserJS plugin. (please use the latest 3.3.1 version of obfuscator)

**Comment by Slapbox** [comment]
@sanex3339 so that means TerserJS is going to undo some of the obfuscation measures, yes? Do we have any idea how much? I'm trying to figure out how to balance between obfuscating just what we need obfuscated, versus obfuscating the whole bundle via the plugin which is going to have serious performance implications.

**Comment by sanex3339** [comment]
Obfuscator has an internal minimizer + simplifier (`compact: true`, `simplify: true` and `identifierNamesGenerator: 'mangled'` options
