### ISSUE TITLE
Missing dependency `webpack-sources`

### ISSUE THREAD

**Issue by aCandidMind** [javascript-obfuscator/webpack-obfuscator#11]
After adding `webpack-obfuscator` to my package.json and successfully installing it, I'm now receiving this when I run my project:
```
1:23:55 rails-static-client-assets.1 | Error: Cannot find module 'webpack-sources'
11:23:55 rails-static-client-assets.1 |     at Function.Module._resolveFilename (module.js:440:15)
11:23:55 rails-static-client-assets.1 |     at Function.Module._load (module.js:388:25)
11:23:55 rails-static-client-assets.1 |     at Module.require (module.js:468:17)
11:23:55 rails-static-client-assets.1 |     at require (internal/module.js:20:19)
11:23:55 rails-static-client-assets.1 |     at Object.<anonymous> (/home/vagrant/dev/www/vpos/backend/client/node_modules/webpack-obfuscator/index.js:2:74)
11:23:55 rails-static-client-assets.1 |     at Module._compile (module.js:541:32)
11:23:55 rails-static-client-assets.1 |     at Object.Module._extensions..js (module.js:550:10)
11:23:55 rails-static-client-assets.1 |     at Module.load (module.js:458:32)
11:23:55 rails-static-client-assets.1 |     at tryModuleLoad (module.js:417:12)
11:23:55 rails-static-client-assets.1 |     at Function.Module._load (module.js:409:3)
```

The [referenced line](https://github.com/javascript-obfuscator/webpack-obfuscator/blob/master/index.js#L2) obviously requires `webpack-sources` and so it should be added as a dependency I guess.

The only thing unclear to me is, why it was working at all for the person in my team who added `webpack-obfuscator` to our project? And I'm also a bit puzzled because I ran dev env and the plugin should only have loaded in production.

**Comment by sanex3339** [comment]
Do you have webpack 1.x?

**Comment by aCandidMind** [comment]
yup
```
"webpack": "^1.12.15",
"webpack-dev-server": "^1.14.1",
```

**Comment by sanex3339** [comment]
I think this is the problem. I made plugin for `2.x` version of webpack and `webpack-sources` package is already bundled into webpack `2.x`

**Comment by aCandidMind** [comment]
But it's somehow working for a co-worker who added `webpack-obfuscator`. Also I just removed my node_modules folder and installed again. Now webpack-sources is there, seemingly provided by `extract-text-webpack-plugin`. No idea why it wasn't needed before. I can run our app again.

Do you advise against using your plugin with the following versions?
```
webpack 1.14.0
webpack-core 0.6.9
webpack-dev-server 1.16.2
webpack-sources 0.1.3
```

**Comment by sanex3339** [comment]
I'm not tested plugin with 1.x version for a half year, so i can't predict any problems.

**Comment by alejandromaka** [comment]
hey there! i think the issue is more related to npm versions < 3 which don't have the flat folder dependencies. when doing a fresh install on our instance (which unfortunately is using node 4 and npm 2) i get this error as well. a good solution would be to add it to peerDependencies, that way it'll only install it when the user doesn't have it already installed.
