### ISSUE TITLE
exclude files inside the bundle

### ISSUE THREAD

**Issue by louistb** [javascript-obfuscator/webpack-obfuscator#114]
Would it be possible to exclude or include files within the bundle ? 
Maybe its possible and i dont understand the plugin fully. 

Im packing a electron app and i dont want the node_modules obfuscated but i want the app code to be.

Right now it seems like its only possible to include/exclude bundles.

Thanks :)

**Comment by sanex3339** [comment]
Hi. Use loader instead of plugin
https://github.com/javascript-obfuscator/webpack-obfuscator#loader-usage

**Comment by louistb** [comment]
Ok got it to work, thanks for the heads up :)

**Comment by sarendsen** [comment]
@sanex3339 I want todo the same for nextjs but it keeps obfuscation everything and does not seem to listen to the exclude option

```javascript
  webpack: (config, options) => {
    if (!options.dev && !options.isServer) {
      config.module.rules.push({
        test: /\\.+(ts|tsx)$/,
        exclude: /node_modules/,
        enforce: 'post',
        use: {
          loader: WebpackObfuscator.loader,
          options: {
            compact: true,
            identifierNamesGenerator: 'mangled',
            selfDefending: true,
            stringArray: true,
            rotateStringArray: true,
            shuffleStringArray: true,
            stringArrayEncoding: [],
            stringArrayThreshold: 0.8,
            splitStrings: true,
            splitStringsChunkLength: 6,
            transformObjectKeys: true,
          }
        }
      })
    }
```
Do you have any pointers?

**Comment by jsjoeio** [comment]
@sarendsen did you ever figure this out?
