### ISSUE TITLE
I want to keep the specified comments after encryption

### ISSUE THREAD

**Issue by webxmsj** [javascript-obfuscator/webpack-obfuscator#115]
Is it possible to keep specified notes, such as copyright information or version number information

**Comment by sanex3339** [comment]
Obfuscator keeps some comments by default, with some reserved keywords:
```
 private static readonly preservedWords: string[] = [
        '@license',
        '@preserve'
    ];
```

So if your comment has these words, it won't be removed after obfuscation.

**Comment by webxmsj** [comment]
ok thanks

**Comment by FabianoLothor** [comment]
How can I change this default behavior?

Terser enables the option to specify my own regex and define which comments I can preserve, would be nice to enable this option in this library too.

**Comment by FabianoLothor** [comment]
Here it's my workaround to anyone who need:

```
    "adjust-comments": "find ./dist -type f -exec sed -i '' 's/ @preserve//g' {} \\;",
    "clean": "rm -rf ./dist/*",
    "build": "npm run clean && webpack --mode production && npm run adjust-comments",
```

The `adjust-comments` script will remove all occurrences of ` @preserve` in all files from `./dist/` folder after the obfuscation.

**Comment by seb-lean** [comment]
where should this be documented? Happy to add it
