### ISSUE TITLE
Error: Cannot find module 'javascript-obfuscator'

### ISSUE THREAD

**Issue by mohasarc** [javascript-obfuscator/webpack-obfuscator#116]
I've just installed `webpack-obfuscator@3.3.0`, imported the module as follows.
```js
const WebpackObfuscator = require('webpack-obfuscator');
```
And used it in my webpack config file as specified in the documentation; however, I am receiving the following error `Error: Cannot find module 'javascript-obfuscator'` when I run webpack. It probably has to do with how the module is exported because I've tried `webpack-obfuscator@2.5.0`, and it worked just fine (tried also all versions between 2.6.0 - 3.3.0 but did not work).

Node v. 12.18.2
webpack v. 4.43.0

**Comment by sanex3339** [comment]
javascript-obfuscator is a peer dependency, so you have to install it manually.

**Comment by mohasarc** [comment]
That worked, thank you!

**Comment by Memories-SlowFever** [comment]
Meaning javascript-obfuscator needs to be specifically installed instead of webpack-obfuscator?
