### ISSUE TITLE
Plugin option for `include` files

### ISSUE THREAD

**Issue by artaommahe** [javascript-obfuscator/webpack-obfuscator#12]
It would be useful to have ability to obfuscate only some (critical) parts of application that can be achieved by passing to plugin an array of file names (/regexp) which should be obfuscated.

**Comment by sanex3339** [comment]
Hi, it is nice idea, when i have time i will do this.
But now you can check this option
https://github.com/javascript-obfuscator/webpack-obfuscator#excludes

**Comment by artaommahe** [comment]
@sanex3339 hm, looks like plugin works over bundles, not separate modules/files, so i dont see clear way to obfuscate only some modules that would be part of final app bundels (e.x. common ng2 bundles `app`, `vendor` and `polyfills` and obfuscated modules should be in one of main bundles, `app` or `vendor`)

**Comment by sanex3339** [comment]
Yes. I see only one way - add to obfuscator option to obfuscate only code inside comments:

```
var abc = 'abc;
/** obfuscator: start **/
// obfuscated code
/** obfuscator: end **/
```

But this feature will have low priority in development plans.

**Comment by artaommahe** [comment]
> add to obfuscator option to obfuscate only code inside comments
yep, this looks enough. Waiting for it )

**Comment by sanex3339** [comment]
Also you can use this webpack plugin 
https://github.com/sanex3339/editable-sources-webpack-plugin

and temporary write same functional for yourself.

**Comment by artaommahe** [comment]
@sanex3339 thx, used this plugin with simple callback, works fine
```js
const JavaScriptObfuscator = require('javascript-obfuscator');


const commentStart = '\\/\\*\\* obfuscator\\: start \\*\\/';
const commentEnd = '\\/\\*\\* obfuscator\\: end \\*\\/';

const replaceRegExp = new RegExp(`${commentStart}(.|[\n\r])+?${commentEnd}`, '');

const obfuscatorOptions = {
  controlFlowFlattening: true,
  rotateStringArray: true,
  stringArray: true,
};


function JavaScriptObfuscatorCallback(sourceCode) {

    const updatedSourceCode = sourceCode.replace(replaceRegExp, (needToObfuscateCode) => {

      const obfuscatedCode = JavaScriptObfuscator.obfuscate(needToObfuscateCode);

      return obfuscatedCode;
    });

    return updatedSourceCode;
}
```

**Comment by sanex3339** [comment]
Also,  controll flow flattening is feature of 0.9.0 version that under development and existing in NPM under `dev` tag. Latest stable version 0.8.3 doesn't have this feature.

**Comment by artaommahe** [comment]
Using comments to determine the boundaries of obfuscation was a bad idea ) If obfuscation is used before `UglifyJS2` than on minification a lot of obfuscated code unfolds. If after - comments are removed and boundaries lost.
Currently bypassed this via replacing comments marks with this dummy code `console.time('obfuscator: start')`/ `console.time('obfuscator: end')` and disable UglifyJS2 `sequences` option :no_mouth:

**Comment by sanex3339** [comment]
Check `javascript-obfuscator@0.12.0` and new conditional comments feature.

**Comment by sabres207** [comment]
@sanex3339 Thanks for the answers and the conditional comments feature.
Is there a way with the conditional comments to tell it where to start and stop obfuscating?
i.e

// other code
// javascript-obfuscator:enable-start
// code to obfuscate
// javascript-obfuscator:enable-end
// other code

**Comment by andrea-citterio-wwit** [comment]
@sanex3339 Is it possible to obfuscate only the service files folder in an Angular project?
Thanks
