### ISSUE TITLE
How do i exclude node_modules with the plugin?

### ISSUE THREAD

**Issue by Directory** [javascript-obfuscator/webpack-obfuscator#125]
This was asked in #109 but nobody answered. i can not use the loader i have to use the plugin. how can i exclude `node_modules` like i do with loaders?

**Comment by Directory** [comment]
would love to get some help with this. my vendors file is nearly 4mb

**Comment by Directory** [comment]
[this](https://github.com/javascript-obfuscator/webpack-obfuscator/pull/15#issuecomment-292963988) seems to work. only downside is you need to have your chunk always named the same. in my case i use `chunkIds: 'deterministic'` so i hardcoded my vendor chunk id like this
```js
  new WebpackObfuscator({...}, ['456.*.js'])
```

**Comment by rinogo** [comment]
You should be able to use something like this (works for me):

```javascript
...
	output: {
		path: path.resolve(__dirname, '..', 'dist'),
		filename: '[name].bundle.js',
	},
	optimization: {
		splitChunks: {
			chunks: 'all',
			name: 'vendor'
		}
	},
 	plugins: [
		new WebpackObfuscator ({
			rotateStringArray: true
		}, ['vendor.bundle.js'])
 	]
...
```
