### ISSUE TITLE
the obfuscator code can not run in IE8

### ISSUE THREAD

**Issue by acgotaku** [javascript-obfuscator/webpack-obfuscator#13]
Because IE8 have not `console` object in normal mode, so the code will trigger error or you have to press `F12` open developer tools.

At last, I have to add  polyfill code before the obfuscator code:

`window.console = window.console || (function(){ 
    var c = {}; c.log = c.warn = c.debug = c.info = c.error = c.time = c.dir = c.profile 
    = c.clear = c.exception = c.trace = c.assert = function(){}; 
    return c; 
})();`

Please check whether  `console` object exists before disable console output.

Thank you !

**Comment by sanex3339** [comment]
Thank you,  i will fix it today

**Comment by sanex3339** [comment]
How i can reproduce this error?

js code:
```js
console.log('it works!!!');
```

In all modes on ie8 when i close Development Tools, refresh page, then open Development Tools, i have no error and message in console 'it works!!!'

with code 
```js
window.console.log = function () {};
console.log('it works!!!');
```

i have no errors and no messages in all modes

**Comment by acgotaku** [comment]
Open IE8 and  load test.html:
`<!DOCTYPE html>
<head>
</head>
<body>
	<script type="text/javascript">
		console.log("Hello World");
	</script>
</body>
</html>`

You will get this warning:
![screenshot from 2017-01-09 23-05-31](https://cloud.githubusercontent.com/assets/1191834/21770870/cde79632-d64a-11e6-8749-eef4a8715da4.png)

I am sorry, this is Chinese.

On the bottom left corner, there's a warning tips. The alert is `console  undefined`.

But If you open the developer tools and reload, the page can run normally.

My IE8 version is 8.0.7601.17514

![screenshot from 2017-01-09 23-09-18](https://cloud.githubusercontent.com/assets/1191834/21771016/60ada844-d64b-11e6-9076-9a36c8c03075.png)

**Comment by sanex3339** [comment]
Still cannot reproduce, same IE version.

But i made fix in separate branch, can you test (for example temporary replace dist/index.js)?
https://github.com/javascript-obfuscator/javascript-obfuscator/tree/0.8.4

If it will work fine i publish new version to npm.

**Comment by acgotaku** [comment]
I have tested it.
No problem. Thank you!

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.8.4` and `webpack-obfuscator@0.8.4` are out.

**Comment by acgotaku** [comment]
nice job! Thank you!
