### ISSUE TITLE
works with ionic2?

### ISSUE THREAD

**Issue by kodeine** [javascript-obfuscator/webpack-obfuscator#17]
hello,
does it work with [ionic2](https://github.com/ionic-team/ionic)? Also i just need to obfuscate my own files not the ionic2 files otherwise it would be a huge js load on browser to execute. please suggest.

**Comment by sanex3339** [comment]
Hi, you should use `CommonChunk` plugin to extract `ionic2` code to `vendor` bundle. Then exclude `vendor` bundle from obfuscation via 
https://github.com/javascript-obfuscator/webpack-obfuscator#excludes

**Comment by kodeine** [comment]
@sanex3339 the issue is ionic chunks the code per page basis so it loads faster on mobile apps. if i combine the vendor then its voids the reason of chunking ionic people chose.

**Comment by tskweres** [comment]
anyone got a working example of an ionic project with this webpack.config setup?

**Comment by Hanzofm** [comment]
+1 to the question

**Comment by JeongJun-Lee** [comment]
+1 to the question and there is a simple tutorial at https://medium.com/front-end-hacking/ionic-and-other-hybrid-apps-code-protection-4561d2a2a605
