### ISSUE TITLE
multimatch should be able accept an array as a second param

### ISSUE THREAD

**Issue by alejandromaka** [javascript-obfuscator/webpack-obfuscator#21]
hey there!

i just noticed that there might be a an issue in the shouldExclude function. right now it's looping through the excludes array and multimatching each individual element https://github.com/javascript-obfuscator/webpack-obfuscator/blob/master/index.js#L61. but as you can see here: https://github.com/sindresorhus/multimatch/blob/master/index.js#L17 multimatch already loops through array in a reduce.

while that isn't an issue in most cases, what is happening to me is that i wish to obfuscate only one file and ignore all others. so my exclude array looks like this ['**/*.js', '!reader/reader-entry.js'] which would work using regular multimatch pattern (https://github.com/sindresorhus/multimatch#usage) but would not work in the module since the first value will always return true and not reach the second exclude element in the array.

i've managed to get around it by wraping the exclude array inside another array (aka. [['**/*.js', '!reader/reader-entry.js']]) and bypassing the initial loop. but ideally shouldExclude function be something like:
```
return multimatch(filePath, exclude).length > 0;
```

anyways, let me know what you think!
thanks!

**Comment by sanex3339** [comment]
Fixed in `0.12.0` version.
