### ISSUE TITLE
not work for webpack 3

### ISSUE THREAD

**Issue by willin** [javascript-obfuscator/webpack-obfuscator#23]
```js
 new JavaScriptObfuscator({
      rotateUnicodeArray: true
    }, ['app.js'])
```

when add to project: https://github.com/AirDwing/webpack-server-bundle

**Comment by sanex3339** [comment]
Any errors?

**Comment by sanex3339** [comment]
Also PR welcomed!

**Comment by willin** [comment]
nothing, bundle.js just like before...

**Comment by dechoiliev** [comment]
Hi,

When i use with/without "webpack.optimize.UglifyJsPlugin()"  is show this error:
Error: Cannot find module 'webpack-sources'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/webpack-obfuscator/index.js:2:100)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by dechoiliev** [comment]
I will change path to "webpack_source" folder where this folder exists. 
In my case is in "webpack/node_modules/". 
Finally is work, but  is not great workaround.

Can you please in the next release fix this case?

**Comment by sanex3339** [comment]
PR welcomed

**Comment by sanex3339** [comment]
@willin you added `app.js` to the excluded files. Correct way is:
```
new JavaScriptObfuscator({
    rotateUnicodeArray: true
});
```

**Comment by sanex3339** [comment]
@dechoiliev cannot reproduce on latest webpack version.

**Comment by dechoiliev** [comment]
My version is 3.6.0.

**Comment by sanex3339** [comment]
Still cannot reproduce.

**Comment by dechoiliev** [comment]
The problem maybe only for my version in ubuntu system. When change the destination path in index.js:

var RawSource = require("webpack-sources").RawSource;
var SourceMapSource = require("webpack-sources").SourceMapSource;

the error never show again.
