### ISSUE TITLE
Is 'disableConsoleOutput' set to true by default?

### ISSUE THREAD

**Issue by MrCoder** [javascript-obfuscator/webpack-obfuscator#24]
When I enable obfuscator, console.log stops printing. I have to do
````
plugins: [
    new JavaScriptObfuscator({
        rotateUnicodeArray: true,
        disableConsoleOutput: false
      }
    )
  ]
````
to enable console. According to this (https://github.com/javascript-obfuscator/javascript-obfuscator#javascript-obfuscator-options) `disableConsoleOutput` is false by default. Not sure where the problem is.

**Comment by sanex3339** [comment]
Interesting, because by default `disableConsoleOutput` is disabled
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/options/presets/Default.ts#L15

What version of `webpack-obfuscator` you using?

**Comment by sanex3339** [comment]
Closed due inactivity
