### ISSUE TITLE
Uncaught ReferenceError: __webpack_require__ is not defined

### ISSUE THREAD

**Issue by cloudprogrammer** [javascript-obfuscator/webpack-obfuscator#26]
![erro](https://user-images.githubusercontent.com/7554320/34638525-3e01854c-f321-11e7-9443-ab3d167a685c.png)

My config file:

```
const webpack = require('webpack');
const JavaScriptObfuscator = require('webpack-obfuscator');
const path = require('path');

const BUILD_DIR = path.resolve(__dirname, './public');
const APP_DIR = path.resolve(__dirname, 'src/');

const config = {
  entry: `${APP_DIR}/index.js`,

  output: {
    path: BUILD_DIR,
    filename: 'bundle.js',
  },
  devServer: {
    historyApiFallback: true,
  },
  module: {
    loaders: [
      {
        enforce: 'pre',
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'eslint-loader',
      },
      {
        test: /\.js$/,
        include: APP_DIR,
        loader: 'babel-loader',
      },
      {
        test: /\.(png|jpg|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: 'images/[name].[ext]',
            },
          },
        ],
      },
      {
        test: /\.(gif|png|jpe?g|svg)$/i,
        use: [
          'file-loader',
          {
            loader: 'image-webpack-loader',
          },
        ],
      },
    ],
  },
  plugins: [
    new JavaScriptObfuscator({
      rotateUnicodeArray: false,
    }),
  ],
};

module.exports = config;
```

My package.json: 
```{
  "name": "whatever",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "babel-preset-stage-2": "^6.24.1",
    "backendless": "^4.3.0",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^4.0.0",
    "eslint-plugin-react": "^6.10.3",
    "react": "^16.0.0",
    "react-bootstrap": "^0.31.5",
    "react-dom": "^16.0.0",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.0.14",
    "redux": "^3.7.2",
    "redux-persist": "^5.4.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "watch": "webpack -d --watch",
    "build": "webpack",
    "serve": "serve ./public"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "file-loader": "^1.1.6",
    "image-webpack-loader": "^3.4.2",
    "serve": "^6.4.3",
    "webpack": "^3.10.0",
    "webpack-obfuscator": "^0.13.0"
  }
}
```

I'm not sure why this is happening, any help is appreciated.

**Comment by sanex3339** [comment]
Without obfuscator everything is ok? Can you send me your project?

**Comment by cloudprogrammer** [comment]
@sanex3339 Yeah everything without the obfuscater works fine, I realised that I didn't want my bundle to be easily read/edited or whatever and I found your loader so I'm trying to implement it now before releasing my app. I don't think I can send you my project but I have replaced my whole app with just one h1 tag that again works without obfuscater but gives the undefined error with the obfuscater plugin applied.

**Comment by sanex3339** [comment]
can you sent me this project with `one h1 tag` that will help me reproduce this error?

**Comment by cloudprogrammer** [comment]
@sanex3339 https://github.com/cloudprogrammer/obfuscate-webpack

**Comment by sanex3339** [comment]
Thank you, i'll check it later today or tomorrow.

**Comment by cloudprogrammer** [comment]
@sanex3339 Thanks man, much appreciated. Awesome thing you've made here.

**Comment by sanex3339** [comment]
Hi, i'll check it today

**Comment by cloudprogrammer** [comment]
@sanex3339 Alright, thank you

**Comment by sanex3339** [comment]
Firstly, this error happens only in `watch` mode. With `build` command everything is ok.

**Comment by sanex3339** [comment]
Secondly, don't use obfuscator in `watch` mode, because of it can make huge compilation slowdown.

**Comment by cloudprogrammer** [comment]
@sanex3339 oh crap haha sorry, I'm new to webpack, I didn't think to check that. Everything seems to be working in build. Thanks man.

**Comment by sanex3339** [comment]
Also, in `watch` mode all code of every webpack module are laced inside `eval`. Obfuscator doesn't working with `eval`.

```
// input
function foo (bar) {
    eval('console.log(\'bar\');');
}

// obfuscated
function _0xabc123(_0xcde456) {
    eval('console.log(\'bar\');');
}

**Comment by cloudprogrammer** [comment]
@sanex3339 Oh right, makes sense. Thank you

**Comment by sanex3339** [comment]
I'll try to implement obfuscation of `eval` expressions here:
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/168

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.14.0-beta.2` with eval expressions obfuscation was published to npm. Please, test it in your projects.

**Comment by serain** [comment]
Any chance this issue creeped back in `0.16.0`? I have no issue without obfuscator, when using obfuscator I get the same `webpack_require`.

I'm running in watch mode and because my use is quite esoteric, I'd like to keep using watch mode with obfuscator if possible.

**Comment by aabbccsmith** [comment]
Was this ever fixed? Still getting this error and removing the obfuscator fixes it, however I need the obfuscator for prod 😄

**Comment by m4heshd** [comment]
Still getting this error on v2.6.0
