### ISSUE TITLE
 'opencollective' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by sudo-shubham** [javascript-obfuscator/webpack-obfuscator#27]
I am getting below error while installing package on windows 10.

> javascript-obfuscator@0.13.0 postinstall E:\frontend\node_modules\javascript-obfuscator
> opencollective postinstall

'opencollective' is not recognized as an internal or external command,
operable program or batch file.'

**Comment by sanex3339** [comment]
Related to https://github.com/opencollective/opencollective-cli
