### ISSUE TITLE
Does not works with third party libraries which are not imported

### ISSUE THREAD

**Issue by js-d-coder** [javascript-obfuscator/webpack-obfuscator#29]
Hi,
Thanks for the library, very useful. I am using this plugin to obfuscate my code. I have installed and added proper entries as per README page but the problem is that my code is not executing. If I remove the plugin and compile again the code works just fine.   
About my settings: I am using some third party libraries and I compile them into a single separate file. Also I don't need to import these in any other JS file. My webpack.config.js file is [here](https://pastebin.com/5yNBLizy)  
I would like to know if there is something I am not doing correctly or not doing at all.  
Thanks again for the help.

**Comment by sanex3339** [comment]
Any errors in the console when you executed code?

**Comment by js-d-coder** [comment]
yeah. errors are too confusing to paste here, but it shows that a variable is undefined.  
Thanks

**Comment by sanex3339** [comment]
Please, paste all errors here. Also i need to know `webpack-obfuscator` version. WIth given config all third-party libraries will be obfuscated, so try to exclude them from obfuscation via `exclude` option.

**Comment by js-d-coder** [comment]
I tried excluding them, but they are getting compiled anyway. my [webpack.config.js](https://pastebin.com/UTQPGxYg)  
thanks

**Comment by sanex3339** [comment]
Please, check example again.
https://github.com/javascript-obfuscator/webpack-obfuscator#excludes

You should use bundle names, so try following:
```
new JavaScriptObfuscator ({
    otateUnicodeArray: false
}, ['thirdparty.js'])
```

**Comment by js-d-coder** [comment]
Thanks for your help. It worked.

**Comment by sanex3339** [comment]
Anyway interesting, why obfuscation of thirdparty triggering errors.

**Comment by js-d-coder** [comment]
Maybe because obfuscator renames the global variables declared in those files. for example, if you just link jquery.js file, obfuscator will rename `jquery`, `$` variables to something else, rendering them useless in dependent files.

**Comment by sanex3339** [comment]
Obfuscator will rename declared global variables only when `renameGlobals` option is enabled.

**Comment by sanex3339** [comment]
But if this thirdparty will use custom DI system based on constructor.toString() like in Angular 1, this code will break.

**Comment by sanex3339** [comment]
Please, can you try to use different versiobs of obfuscator 0.12.0, 0.13.0, 0.14.0 and obfuscate your thirdparty? Errors will happen with all versions?
