### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Marcotrombino** [javascript-obfuscator/webpack-obfuscator#30]
Hi, I'm developing a desktop app with Electron + React and I want to obfuscate my code.
I'm facing an issue when I add a JavaScriptObfuscator on my plugins queue: on the served html page I have an error saying
```javascript 
main.js:1 Uncaught RangeError: Maximum call stack size exceeded
```
This happens **independently** from the obfuscator options except for empty options. The one I'm trying right now is the following (which should be the "Low obfuscation, High performance") :
```javascript 
new JavaScriptObfuscator ({
    compact: false,
    controlFlowFlattening: false,
    deadCodeInjection: false,
    debugProtection: false,
    debugProtectionInterval: false,
    disableConsoleOutput: true,
    identifierNamesGenerator: 'hexadecimal',
    log: false,
    renameGlobals: false,
    rotateStringArray: true,
    selfDefending: true,
    stringArray: true,
    stringArrayEncoding: false,
    stringArrayThreshold: 0.75,
    unicodeEscapeSequence: false
}, [])
```

To be more clear here is my webpack.config.js (I use **Webpack 4.1.1**):
```javascript 
const HtmlWebPackPlugin = require("html-webpack-plugin");
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const JavaScriptObfuscator = require('webpack-obfuscator');
const path = require('path');

module.exports = {
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      },
      {
        test: /\.html$/,
        use: [
          {
            loader: "html-loader",
            options: { minimize: true }
          }
        ]
      },

      {
        test: /\.css$/,
            loader: 'style-loader!css-loader?modules=true&localIdentName=[name]__[local]___[hash:base64:5]'
      }

    ]
  },
  plugins: [
    new JavaScriptObfuscator ({
    compact: false,
    controlFlowFlattening: false,
    deadCodeInjection: false,
    debugProtection: false,
    debugProtectionInterval: false,
    disableConsoleOutput: true,
    identifierNamesGenerator: 'hexadecimal',
    log: false,
    renameGlobals: false,
    rotateStringArray: true,
    selfDefending: true,
    stringArray: true,
    stringArrayEncoding: false,
    stringArrayThreshold: 0.75,
    unicodeEscapeSequence: false
    }, []),

    new HtmlWebPackPlugin({
      template: "./src/index.html",
      filename: "./index.html"
    }),
    new ExtractTextPlugin("./styles.css")
  ]
};
```

**Comment by sanex3339** [comment]
Try to disable `selfDefending` option. It will work.

**Comment by Marcotrombino** [comment]
Amazing, it works thanks! 
Is it a bug?

**Comment by sanex3339** [comment]
Looks like something was modified obfuscated code and this triggered self defending mechanism. Your error is self defending mechanism.

**Comment by Marcotrombino** [comment]
Is there something I can do to check what is it? I'm a webpack newbie, but given that webpack.config.js I don't see anything which could modify my obfuscated code, I just compile my code before with babel and nothing more

**Comment by sanex3339** [comment]
I don't know. Self defending mechanism is triggering when code will reformatted (beautifying) or strings in unicode escape sequence format will replaced on a normal format.

So, maybe some other plugin or webpack itself was changed obfuscated code in some way.

**Comment by sanex3339** [comment]
Closed due inactivity

**Comment by teodoz** [comment]
> Try to disable `selfDefending` option. It will work?

You are a lifesaver. Saved me in the last minutes until I needed to show my code to my team. Thank you!
