### ISSUE TITLE
Include instead of exclude

### ISSUE THREAD

**Issue by SuperOP535** [javascript-obfuscator/webpack-obfuscator#33]
Title says it all

**Comment by SuperOP535** [comment]
perhaps you should make third arg true for include, false for exclude

**Comment by sanex3339** [comment]
Hi. Exclude array accepts `glob` strings, so try to use syntax like:

Glob:
```
/**/!(abc).js
``` 

```
/src/test/foo.js // will exluded
/src/test/bar.js // will exluced
/src/test/folder/foo.js // will exluded
/src/foo/abc.js // will included
/src/foo/abcd.js // will included
```

**Comment by yourfavorite** [comment]
I've been playing with this and can't seem to get a single glob to use exclude to include multiple files in different directories. I think an include param would be super useful.

Files I want to include:
```
/app/lib/file.js
/app/lib/my-folder/one.js
/app/lib/my-folder/two.js
```

To match these I can do: `**/!(file)*` or `**/!(my-folder)/*` but I can't find a way to get both in the same exclude glob.

**Comment by SuperOP535** [comment]
Closed in favor of [obfuscator-loader](https://github.com/javascript-obfuscator/obfuscator-loader) which is much more convenient and allows using a regular expression to which files to include.
