### ISSUE TITLE
Doesn't work with Vue

### ISSUE THREAD

**Issue by alijaya** [javascript-obfuscator/webpack-obfuscator#36]
Hi... I try to make it works with vue... but it keeps showing an error, and the error somehow changes each compilation.

How to reproduce:
1. make a project with `vue create`
2. cd to the project and add `webpack-obfuscator` (i do it with yarn, `yarn add webpack-obfuscator`)
3. add file `vue.config.js`, write this:

> var JavaScriptObfuscator = require('webpack-obfuscator')
> 
> module.exports = {
>   configureWebpack: {
>     plugins: [
>       new JavaScriptObfuscator()
>     ]
>   }
> }

4. serve it (i use yarn, so `yarn serve`)
5. open the page, open the console, and you see the error

**Comment by diaevd** [comment]
Obfuscator working only with vue-cli configuration for TypeScript :(

**Comment by sanex3339** [comment]
Try to obfuscate your bundle directly with javascript-obfuscator. Error will happen?

**Comment by alijaya** [comment]
@sanex3339 : do you mean to use javascript-obfuscator cli to the js build file?

**Comment by alijaya** [comment]
I've tried it... it could work with certain settings... but how I could integrate this in webpack?

**Comment by sanex3339** [comment]
Strange that it doesn't work, because it just obfuscating bundle.
You can try obfuscate bundle without webpack-obfuscator plugin, with
https://www.npmjs.com/package/editable-sources-webpack-plugin

Anyway, i'll look into this issue when i'll have a time.

**Comment by alijaya** [comment]
Ok... I have toying with this plugin... so I've found out that... in this line

```
this.excludes = typeof excludes === 'string' ? [excludes] : excludes || [];
```

Will be error if excludes is undefined (when you call `JavaScriptObfuscator()`, without parameter)

So I suggest to change it to:

```
excludes = excludes || [];
this.excludes = typeof excludes === 'string' ? [excludes] : excludes;
```

It's now working with `yarn build`
But still have a warning because in this code, you use deprecated API, you use this:

`compiler.plugin('compilation', (...) => {...})`

instead of this:

`compiler.hooks.compilation.tap('PluginName', (...) => {...})`

for `yarn serve`, I haven't found the solution, it compiles, but it still shows error in the browser. I think it's because the hot reloading code from vue-cli... :-?... I'll tinker around a little bit

**Comment by peteringram0** [comment]
Also getting issues here. Any full solution for this yet?

**Comment by crimbler2** [comment]
For anyone seeing this: try setting the parameter "seed" to 0
