### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Webpack 4

### ISSUE THREAD

**Issue by WaqasIbrahim** [javascript-obfuscator/webpack-obfuscator#38]
Hi, When using Webpack 4 I receive the following warning message:

```bash
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at WebpackObfuscator.apply (../../node_modules/webpack-obfuscator/index.js:16:18)
```

The warning can be fixed by using the new hooks API and replacing
```javascript
compiler.plugin('compilation', function (compilation) {
    compilation.plugin("optimize-chunk-assets", function (chunks, callback) {
```
With this:
```javascript
compiler.hooks.compilation.tap('WebpackObfuscator', function (compilation) {
    compilation.hooks.optimizeChunkAssets.tap('WebpackObfuscator', function (chunks) {
```
And removing the callback call. You can also keep backwards compatibility. Please take a look at my commit [here](https://github.com/WaqasIbrahim/webpack-obfuscator/blob/d6ec33860cc06dd1309fc3bcc428fbb1f6a63edb/index.ts#L37).

**Comment by yourapiexpert** [comment]
How long does it take to merge?!

**Comment by yourapiexpert** [comment]
@WaqasIbrahim Would you be so king as to submit a PR so that this can be merged?

**Comment by WaqasIbrahim** [comment]
@yourapiexpert, I upgraded major versions of packages in that commit so I am not sure If the author would want that.
