### ISSUE TITLE
souceMap?

### ISSUE THREAD

**Issue by Lonniebiz** [javascript-obfuscator/webpack-obfuscator#39]
Is souceMap a misspelling on the main page of this project? Shouldn't that be sourceMap?

**Comment by konstantin24121** [comment]
Yea it's misspelling but sourceMap not working now. Anyway, @sanex3339 any progress with generating source maps?

**Comment by Lonniebiz** [comment]
You guys need to tighten up your game. I don't like reading misspelled words. There's no exquse for it.

**Comment by konstantin24121** [comment]
> You guys need to tighten up your game. I don't like reading misspelled words. There's no exquse for it.

*excuse

**Comment by Lonniebiz** [comment]
Intentionally. I'm glad you finally noticed.

**Comment by sanex3339** [comment]
Closed as old. Please try on latest version.
