### ISSUE TITLE
Update to javascript-obfuscator 0.18.2

### ISSUE THREAD

**Issue by Enrico204** [javascript-obfuscator/webpack-obfuscator#44]
There are any plan to release a new version that uses javascript-obfuscator >= 0.18.2 ? There are some bugfix (as this one https://github.com/javascript-obfuscator/javascript-obfuscator/issues/320 ) that made me lose an entire day to debug.

Thanks for all your work :-)

**Comment by zamotkin** [comment]
Yes, the latest version is 0.18.7
