### ISSUE TITLE
default configuration of webpack-obfuscator

### ISSUE THREAD

**Issue by xiaolannuoyi** [javascript-obfuscator/webpack-obfuscator#48]
I want to know what the default configuration of webpack-obfuscator is?

**Comment by mauricedoepke** [comment]
@xiaolannuoyi  The same as for JavascriptObfuscator: https://github.com/javascript-obfuscator/javascript-obfuscator/blob/605f25075a1857ddfab7c3422638bbab23e42cb4/src/options/presets/Default.ts
