### ISSUE TITLE
Problem with react project

### ISSUE THREAD

**Issue by wilmanh** [javascript-obfuscator/webpack-obfuscator#49]
Hi, thank you for the great work you have done here, i am try to obfuscate a react project, and it almost works!!! except for a tiny problem, the html generated by jsx remove all the splaces for /x20 and print it that way (blablabla\x20blabla), it happens in the class property to (class='button\x20btn'). there is a way to omit this behavior?

**Comment by mauricedoepke** [comment]
I have got the same problem looks like the \x20 get escaped to \\\\x20 somewhere in the process and thus being displayed in strings.
