### ISSUE TITLE
If I can unobfuscator my code whithout node_modules library?

### ISSUE THREAD

**Issue by everlose** [javascript-obfuscator/webpack-obfuscator#50]
I use some library in node_modules，but webpack-obfuscator act on `compilation.assets`，so all my code and library obfuscator。

**Comment by mauricedoepke** [comment]
You need to create two separate bundles, one with your one code and one with the node_modules. Then you tell the obfuscator to ignore the node_modules bundle.

Add the following to your webpack config to create different bundles for your own code and for libraries.
```
    optimization: {
        splitChunks: {
            cacheGroups: {
                vendor: {
                    test: /node_modules/,
                    chunks: 'initial',
                    name: 'vendor',
                    enforce: true
                },
            }
        }
    },
```
And then tell the obfuscator to ignore the node_modules bundle with:
```
        new JavaScriptObfuscator({
        }, ['**_vendor.js'])
```

You might have to change '**_vendor.js' to fit your filenames

**Comment by techterbium** [comment]
I just ran into this problem. I tried to configure `excludes` to ignore all node_modules but it did not work.

 ```
       new JavaScriptObfuscator({
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 0.75,
            deadCodeInjection: true,
            log: false,
            rotateUnicodeArray: true
        }, ['node_modules/**/*.js'])
```

Can you help me with working example?

**Comment by TorRanfelt** [comment]
@techterbium Excludes are on the generated files. Not on the original source files.

**Comment by vesper8** [comment]
took me a few tries to figure this out but got it working. In my case I use vue-cli and all my custom javascript is labeled uniquely thanks to `webpackChunkName`

So what I wanted to do was obfuscate all of that but not obfuscate the vendor files which create bundles that start with `chunk-` and `app-`

Anyway I may still have some testing to do to make sure all my proprietary code is obfuscated, but this is what I used to exclude all bundles that start with `chunk-` and `app-`

```
const obfuscatorPlugin = new JavaScriptObfuscator({
  rotateUnicodeArray: true,
}, [
  '**/app-*.js',
  '**/chunk-*.js',
]);
```

**Comment by sanex3339** [comment]
Closed as old. Fell free to create a new issue.
