### ISSUE TITLE
Wrap output in IIFE

### ISSUE THREAD

**Issue by thepatrick** [javascript-obfuscator/webpack-obfuscator#56]
This library (and `javascript-obfuscator` itself) are immensely useful - thank you!

I do wish that it didn't add additional variables to `window`, so would it possible to (optionally?) wrap the output in an IIFE?

Right now I'm doing it myself with a custom webpack plugin, because every option I threw webpack to try and make it do it just applied _before_ webpack-obfuscator does its thing.

**Comment by sanex3339** [comment]
No, i won't plan this

**Comment by thepatrick** [comment]
I’ve since moved on to using alternative obfuscation tools anyway - but thank you for this project!
