### ISSUE TITLE
webpack-obfuscator doesn't do anything after having followed instructions

### ISSUE THREAD

**Issue by TorRanfelt** [javascript-obfuscator/webpack-obfuscator#57]
For some reason I can't get webpack-obfuscator to obfuscate anything.

Installed:
npm install --save-dev webpack-obfuscator

Imported:
const JavaScriptObfuscator = require('webpack-obfuscator');

Inserted into plugins:
new JavaScriptObfuscator()

No errors but the output is as before.

**Comment by TorRanfelt** [comment]
I got it to work through obfuscator-loader. However, I would rather use webpack-obfuscator.

module: {
            rules: [
                {
                    test: /\.js$/,
                    include: [somePath],
                    enforce: 'post',
                    use: {
                        loader: 'obfuscator-loader',
                        options: {
                            compact: true
                        }
                    }
                }
            ]
        }

**Comment by star-collector** [comment]
I have encountered the same problem. It seems like all versions of this plugin above 0.18.0 are broken. 0.18.0 works just fine.

**Comment by sanex3339** [comment]
0.18.1+ versions are required webpack@4.3.0+

**Comment by star-collector** [comment]
@sanex3339 I use webpack@4.35.3 (latest) and still face the same issue. 0.18.1 and 0.18.2 just don't work for me.

**Comment by paul321** [comment]
Same issue here the plugin doesn't do anything

**Comment by sanex3339** [comment]
Did you all are use plugin without any options? Just raw `new JavaScriptObfuscator()`?

**Comment by paul321** [comment]
No, i have the following options:

new JavaScriptObfuscator({
            rotateUnicodeArray: true,
            compact: true,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 0.75,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 0.4,
            debugProtection: true,
            debugProtectionInterval: true,
            disableConsoleOutput: true,
            rotateStringArray: true,
            selfDefending: true,
            stringArray: true,
            stringArrayEncoding: true,
            stringArrayThreshold: 0.8,
            unicodeEscapeSequence: true
        })

Working fine in 0.18.0!

**Comment by sanex3339** [comment]
@paul321 what webpack version you are using?

**Comment by paul321** [comment]
Version: webpack 4.35.2

**Comment by star-collector** [comment]
@sanex3339 I use only rotateUnicodeArray.

**Comment by sanex3339** [comment]
Don't know how to reproduce this bug. For me with webpack 4.3.0 all works fine with this config:
https://github.com/javascript-obfuscator/webpack-obfuscator/blob/master/test/config/webpack.config.js

**Comment by sanex3339** [comment]
O, looks like something happen now

**Comment by sanex3339** [comment]
please try 0.18.3

**Comment by star-collector** [comment]
@sanex3339 Yes, the obfuscation seems to be working again. Thanks.

**Comment by TorRanfelt** [comment]
@sanex3339 It's working with the new release. Thank you.
