### ISSUE TITLE
Error in TS config

### ISSUE THREAD

**Issue by yovanoc** [javascript-obfuscator/webpack-obfuscator#58]
Hello, I have a problem with a webpack.config.ts

![image](https://user-images.githubusercontent.com/7302317/64163034-c29feb80-ce40-11e9-8dca-1a97d8394f41.png)

for target and identifierNamesGenerator  we can't go that way unless the ts-ignore because you are using an enum. Could it be better with a union type?

**Comment by yovanoc** [comment]
Any news on that?

**Comment by yovanoc** [comment]
This repo sill maintained?

**Comment by zamotkin** [comment]
I'm closing it as duplicate issue.
