### ISSUE TITLE
Error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Neuroforge** [javascript-obfuscator/webpack-obfuscator#60]
Hello,

Thank you for this project, it is awesome and works so well! However, recently we have Forked our own version of TensorflowJs.  We want to hide some of the changes in our code.

> (index):1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

TensorflowJs is available form here.

https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.0.0/dist/tf.min.js

Any thoughts on how to resolve this issue?

<img width="578" alt="Screen Shot 2019-10-02 at 11 49 26 AM" src="https://user-images.githubusercontent.com/1474186/66012468-b627b500-e50a-11e9-85e8-35a27fccd1e8.png">

**Comment by teodoz** [comment]
> 

Sorry for the 2 years answer. Just saw you closed the issue. Have you found the solution? Thanks!
