### ISSUE TITLE
Issue with OpenCollective postinstall when installing on FreeBSD

### ISSUE THREAD

**Issue by brianreichtcs** [javascript-obfuscator/webpack-obfuscator#63]
I'm running into an issue that numerous other npm packages have run into with old versions of opencollective.  The postinstall process fails, causing the webpack-obfuscator install to fail.

https://github.com/ng-packagr/ng-packagr/issues/1178

Error:
`> core-js@2.6.10 postinstall /data/ccp/node_modules/babel-polyfill/node_modules/core-js
> node postinstall || echo "ignore"

internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '/data/ccp/node_modules/babel-polyfill/node_modules/core-js/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
ignore

> core-js@2.6.10 postinstall /data/ccp/node_modules/babel-runtime/node_modules/core-js
> node postinstall || echo "ignore"

internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '/data/ccp/node_modules/babel-runtime/node_modules/core-js/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
ignore

> javascript-obfuscator@0.18.1 postinstall /data/ccp/node_modules/javascript-obfuscator
> opencollective postinstall

sh: opencollective: Permission denied
npm WARN gulp-typescript@5.0.1 requires a peer of typescript@~2.7.1 || >=2.8.0-dev || >=2.9.0-dev || ~3.0.0 || >=3.0.0-dev || >=3.1.0-dev || >= 3.2.0-dev || >= 3.3.0-dev but none is installed. You must install peer dependencies yourself.
npm WARN tsickle@0.37.0 requires a peer of typescript@~3.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN tsify@4.0.1 requires a peer of typescript@>= 2.x but none is installed. You must install peer dependencies yourself.
npm WARN demo@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! javascript-obfuscator@0.18.1 postinstall: `opencollective postinstall`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the javascript-obfuscator@0.18.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-17T12_47_17_256Z-debug.log
`

**Comment by zamotkin** [comment]
@brianreichtcs do you have this issue in the latest 0.18.7 release?

**Comment by sanex3339** [comment]
Hi. I changed opencollective package on the other one. I will publish the a version later today. Please try it.
