### ISSUE TITLE
works great! any chance this could also be used to obfuscate css?

### ISSUE THREAD

**Issue by vesper8** [javascript-obfuscator/webpack-obfuscator#70]
Happy to report this seems to work perfectly for obfuscating my vue-cli v4 project. Was super easy to configure and get working too.

Since I'm using Tailwind CSS as my main CSS framework now and as a result styles are easier than ever to rip and steal, I was wondering if this could also be used to obfuscate the css classes both in the html as well as in the css bundles?

On a side note, I did notice that obfuscating essentially doubles the size of all javascript files.. I guess this is normal and there's no way to lessen that is there?

Thanks for making and maintaining this!

**Comment by sanex3339** [comment]
Hi. It wont support css.
About code size, in the upcoming 0.25.0 release it will contain improved mangled identifier names generator. It will slightly decrease output code size
