### ISSUE TITLE
Solutions to fix sourcemap problem

### ISSUE THREAD

**Issue by sxwxs** [javascript-obfuscator/webpack-obfuscator#75]
Hi, I am working on fixing the bug in sourcemap support. The current code only handles .js asserts, but in the emit stage of webpack, changes made to a .js assert object cannot be applied to its corresponding sourcemap file.

I came up with two solutions to fix this problem. 
The first is to modify the hook stage which may involve more modifications. The second way is to process both the .js asserts and the corresponding .map asserts when require sourcemap, but the problem is we need an additional variable to allow .map asserts to access the obfuscator output.

I've implemented the second solution in my fork([commit](https://github.com/sxwxs/webpack-obfuscator/commit/8c0e1191332e0c344c2f5e842f99dcbdd8eb0e3c)) and it's passed the test. I'd like to make a pull request if you think that's okay.

**Comment by sanex3339** [comment]
Thank you. PR welcomed!

**Comment by sanex3339** [comment]
Merged, thank you!
