### ISSUE TITLE
Error:  Cannot find module 'webpack-obfuscator/loader'

### ISSUE THREAD

**Issue by Strulle** [javascript-obfuscator/webpack-obfuscator#82]
I've added 
```
{
  ...
  loader: `webpack-obfuscator/loader`
  ...
}
```

 to my webpack config. When building my App (vue.js) the module cannot be resolved.

using `loader: path.resolve(__dirname, './node_modules/webpack-obfuscator/dist/loader')` works as expected.

Versioninformation:
- OS: macOS Catalina 10.15.5
- node: v12.16.2
- webpack: 4.43.0
- webpack-obfuscator: 1.8.1

If you need further information, please let me know

**Comment by sanex3339** [comment]
I expected this =( Right now use `path.resolve(__dirname, './node_modules/webpack-obfuscator/dist/loader')`. I have to think about how to fix it.

**Comment by sanex3339** [comment]
Have to do something similar to this:

**Comment by sanex3339** [comment]
Updated to `1.8.2`.
Use loader like described here:
var WebpackObfuscator = require('webpack-obfuscator');

// webpack loader rules array
rules: [
    {
        test: /\.js$/,
        exclude: [ 
            path.resolve(__dirname, 'excluded_file_name.js') 
        ],
        enforce: 'post',
        use: { 
            loader: WebpackObfuscator.loader, 
            options: {
                rotateStringArray: true
            }
        }
    }
]
```

**Comment by sanex3339** [comment]
If something goes wrong again - let me know

**Comment by Strulle** [comment]
It is working now, thank you for your quick reply.

**Comment by enkr1** [comment]
Solved w this:
https://www.npmjs.com/package/javascript-obfuscator
