### ISSUE TITLE
webpack-obfuscator not working with mapbox gl in react js

### ISSUE THREAD

**Issue by Vgurnani** [javascript-obfuscator/webpack-obfuscator#85]
![image](https://user-images.githubusercontent.com/32096089/89666252-a41b5d80-d8f7-11ea-8d93-11e4d0487fbb.png)

The code is broken on a production build. It's not working with mapbox gl

**Comment by sanex3339** [comment]
Need more information

**Comment by sanex3339** [comment]
Can you create a reproduceable small example with this problem?

**Comment by Vgurnani** [comment]
This issue is not generated on code pan bcz server is not restarted after adding rewired library, 
Please follow these steps:-
step 1.npx create-react-app test
step 2.npm i  webpack-obfuscator
step 3. npm i react-app-rewired
step 4. Please create config-overrides.js file on the root level and paste this code

var WebpackObfuscator = require("webpack-obfuscator");

module.exports = function override(config, env) {
  config.plugins.push(
    new WebpackObfuscator(
      {
        rotateStringArray: true
      },
      ["bundles/**/**.js"]
    )
  );
  return config;
};

step 5. 
  /* package.json */
 
  "scripts": {
-   "start": "react-scripts start",
+   "start": "react-app-rewired start",
-   "build": "react-scripts build",
+   "build": "react-app-rewired build",
-   "test": "react-scripts test",
+   "test": "react-app-rewired test",
    "eject": "react-scripts eject"
}

step 5.npm i mapbox-gl
step 6. please create file locationMap.js and paste this code

import React, { useEffect, useRef, useState } from "react";
import mapboxgl from "mapbox-gl/dist/mapbox-gl.js";
import PropTypes from "prop-types";

var map;

const LocationMap = props => {
  const mapContainer = useRef(null);
  const [coordinates] = useState([-0.1262362, 51.5001524]);
  const [zoom] = useState(1);
  const initMapboxAndSlider = () => {
    mapboxgl.accessToken =
      "pk.eyJ1Ijoidmd1cm5hbmkiLCJhIjoiY2s2NmF5ZXpmMTAxdTNsbnI3dmh4cTJ3ZiJ9.rPIHv99-UOJ2ZRbX3Sb-hg";
    map = new mapboxgl.Map({
      container: mapContainer.current,
      style: "mapbox://styles/mapbox/streets-v11",
      center: coordinates,
      zoom: zoom,
      attributionControl: false,
      maxZoom: 8,
      minZoom: 1
    });
    // map.setRenderWorldCopies(false)
    map.on("load", () => {
      map.resize();
    });
    map.dragRotate.disable();
  };

  useEffect(() => {
    map && map.remove();
    initMapboxAndSlider();
  }, []);

  return <div className="location-map" ref={mapContainer} />;
};

LocationMap.propTypes = {
  location: PropTypes.object
};

export default LocationMap;

step 7. call this component in app.js file

import React from "react";
import "./styles.css";
import LocationMap from "./mapLocations";
export default function App() {
  return (
    <div className="App">
      <LocationMap />
    </div>
  );
}

step 8. npm start
then you will get this error
https://user-images.githubusercontent.com/32096089/89666252-a41b5d80-d8f7-11ea-8d93-11e4d0487fbb.png

**Comment by rohitt863** [comment]
Yes, I am getting the same issue. 
Pls follow this steps
1.clone this URL
https://github.com/rohitt863/map-issue.git
2. run this command
npm install
3.then start server using this command
 npm start
then you get this issue
![image](https://user-images.githubusercontent.com/52744595/89880816-50a05c80-dbe2-11ea-9bd6-cf18c8d503ce.png)

**Comment by sanex3339** [comment]
This is because `mapbox-gl` creates WebWorker from obfuscated function:
```
new Worker(function() {
    // here is obfuscated code of `mapbox-gl` function that is using as worker code
});
```

To avoid it you have to use the separate worker script:
https://docs.mapbox.com/mapbox-gl-js/api/#csp-directives

```
mapboxgl.workerUrl = "./mapbox-gl-csp-worker.js";
```

The problem with this approach is CRA, I don't know how to serve the worker script with it (by default it opens worker script as `html` file.
But with custom `express` server it works:
```
// server.js
const express = require('express');
const path = require('path');
const app = express();
app.use(express.static(path.join(__dirname, 'build')));
app.get('/', function(req, res) {
    res.sendFile(path.join(__dirname, 'build', 'index.html'));
});
app.get('/mapbox-gl-csp.worker.js', function(req, res) {
    res.sendFile(path.join(__dirname, 'build', 'static', 'js', 'mapbox-gl-csp.worker.js'));
});
app.listen(3000);
```

![image](https://user-images.githubusercontent.com/9210534/89885813-48412500-dbd4-11ea-9cd4-d4d035735c32.png)

So, to conclude, `javascript-obfuscator` doesn't work with WebWorkers that are created directly from the function, because after these workers are created, they have separate global scope and this scope haven't access to the `string-array` function.

In this situation you have few choices:
- use `mapboxgl.workerUrl` and separate worker script
- disable obfuscation of worker's function with the `conditional-comments`. This is not your case because this code is third-party code.
