### ISSUE TITLE
v1.8.1 breaks TypeScript support - index.d.ts has empty export

### ISSUE THREAD

**Issue by msheakoski** [javascript-obfuscator/webpack-obfuscator#90]
Commit 6844df0 causes index.ts to have an empty export `export {};` when using the npm package.

It is no longer possible to import the package in TypeScript using `import WebpackObfuscator from "webpack-obfuscator"` and if you use `const WebpackObfuscator = require("webpack-obfuscator")` you do not get IDE auto-completion.

**Comment by sanex3339** [comment]
Try `1.11.1` version.
