### ISSUE TITLE
HEAPU32 is not defined

### ISSUE THREAD

**Issue by telubato** [javascript-obfuscator/webpack-obfuscator#92]
Hi,

After add lib @react-pdf/renderer on my project, my project can't be load, appears a error message:

"VM186:1 Uncaught ReferenceError: HEAPU32 is not defined
    at Function.eval [as bind_value] (eval at _0x3ee8ff (bundle.js?version=prod:98), <anonymous>:1:27)

Any idea?
Thank you.

**Comment by sanex3339** [comment]
I may suggest that this is related with web worker and similar to https://github.com/javascript-obfuscator/webpack-obfuscator/issues/85 issue.

**Comment by telubato** [comment]
Hi,

After split the code from node-modules, and not ofuscated modules, issue was solved.
I think that problem was related with size of bundle.
Thank you.

**Comment by djaffer** [comment]
I am facing this same issue. 
![image](https://user-images.githubusercontent.com/5740725/141677647-bf19ed7a-c089-433e-b309-60b8638c0318.png)

**Comment by tult-rk** [comment]
@djaffer I have the same issue today. Are you use nextjs 12 with swc for transpileing code. If yes, you could try to set `swcMinify = false` in `next.config.js`. It works for me

**Comment by djaffer** [comment]
I am using react. I got it to work by separating out node modules.

The documentation can have these configs as this is such a common issue. Have such a cool plugin but horrible documentation.

config.optimization.splitChunks = {
      cacheGroups: {
        vendor: {
          test: /node_modules/,
          chunks: 'initial',
          name: 'vendor',
          enforce: true,
        },
      },

    new WebpackObfuscator(
        {
          rotateStringArray: true,
        },
        ['**/vendor.*.chunk.js']
      )
    );
    
    Credit to @mauricedoepke  #50  otherwise I would have been stuck on this.

**Comment by djaffer** [comment]
I am using react. I got it to work by separating out node modules. The documentation can have these configs as this is such common issue.
```
config.optimization.splitChunks = {
      cacheGroups: {
        vendor: {
          test: /node_modules/,
          chunks: 'initial',
          name: 'vendor',
          enforce: true,
        },
      },

    new WebpackObfuscator(
        {
          rotateStringArray: true,
        },
        ['**/vendor.*.chunk.js']
      )
    );
    ```
    Credit to @maccesch mauricedoepke #50

**Comment by lakindu2002** [comment]
> @djaffer I have the same issue today. Are you use nextjs 12 with swc for transpileing code. If yes, you could try to set `swcMinify: false` in `next.config.js`. It works for me

This worked like a charm!

**Comment by erlangparasu** [comment]
@djaffer which file need to be editted?

**Comment by erlangparasu** [comment]
@telubato @djaffer which file need to be editted?

**Comment by djaffer** [comment]
webpack, config.js
