### ISSUE TITLE
webpack-obfuscator and webpack.BannerPlugin

### ISSUE THREAD

**Issue by tamis-laan** [javascript-obfuscator/webpack-obfuscator#93]
I'm using the webpack.BannerPlugin (https://webpack.js.org/plugins/banner-plugin/) to add a banner to my bundle. This works in development mode but it doesn't work in production mode where I'm using webpack-obfuscator to obfuscate the code. The obfuscator removes the banner from the bundle as it is technically a comment. 

I tried to change the order of the plugins so the obfuscator would run first and then the banner would be injected, however this failed. It looks like webpack decides the run order of the plugins based on some other criterion. 

Is there some way to get both working together? Or does webpack-obfuscator supply some method to inject a banner as a post process?

**Comment by sanex3339** [comment]
Just add `@preserve` to your comment

**Comment by sanex3339** [comment]
Closed. Feel free to reopen a new issue.
