### ISSUE TITLE
Plugin may not work in webpack 5

### ISSUE THREAD

**Issue by jakebailey** [javascript-obfuscator/webpack-obfuscator#94]
webpack 5 is due to be released pretty shortly; this plugin works fine in webpack 5 at the moment but may not in the future due to deprecations in the API. Running the plugin shows me:

```
(node:90055) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Because the obfuscator plugin appears to be modifying the assets directly. I don't know quite enough about webpack to know what all is involved.

**Comment by sanex3339** [comment]
I released `webpack-obfuscator@3.0.0-beta.0` with the support of webpack@5, but I dropped the support of webpack@4.
`javascript-obfuscator` now is a `peerDependency`.
I'll release `webpack-obfuscator@2.6.0` with the support of webpack@4 and `javascript-obfuscator` as a `peerDependency` today too.

**Comment by sanex3339** [comment]
Support both 4 and 5 more complicated. The problem starts with the typings and ends with different API.

**Comment by jakebailey** [comment]
Unfortunate. Hopefully people are content to stay on v2 for webpack 4, then.

**Comment by sanex3339** [comment]
For @4 i'll publish version `2.6.0`.
